kind: pipeline
type: docker
name: default

trigger:
  event:
    - push

steps:
  - name: sonar-analyses
    image: hub.codefirst.iut.uca.fr/camille.petitalot/drone-sonarplugin-reactnative:latest
    commands:
      - cd Sources
      - npm install
      - sonar-scanner -Dsonar.projectKey=React-eat -Dsonar.sources=. -Dsonar.host.url=$${PLUGIN_SONAR_HOST} 
        -Dsonar.login=$${PLUGIN_SONAR_TOKEN}
    secrets: [ SECRET_SONAR_LOGIN ]
    settings:
      sonar_host: https://codefirst.iut.uca.fr/sonar/
      sonar_token:
        from_secret: SECRET_SONAR_LOGIN
    when:
      branch:
        - master